/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SelectionOption } from './selectionOption';


export interface BasketItem { 
    discountPerc?: number;
    name?: string;
    options?: Array<SelectionOption>;
    price?: number;
    quantity?: number;
    image?: string;
}
