/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SelectionOption } from './selectionOption';


export interface Stock { 
    description?: string;
    discountPerc?: number;
    images?: Array<string>;
    mandatorySelection?: Array<SelectionOption>;
    name?: string;
    id?: string;
    optionalSelection?: Array<SelectionOption>;
    price?: number;
    quantity?: number;
}
