/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Bank } from './bank';


export class UserProfile { 
    address?: string;
    badges?: number;
    bank?: Bank;
    date?: Date;
    description?: string;
    id?: string;
    idNumber?: string;
    imageUrl = "https://pbs.twimg.com/media/C1OKE9QXgAAArDp.jpg";
    latitude?: number;
    likes?: number;
    longitude?: number;
    mobileNumber?: string;
    emailAddress?: string;
    modifiedDate?: Date;
    name?: string;
    surname?: string;
    responseTimeMinutes?: number;
    role: UserProfile.RoleEnum;
    servicesCompleted?: number;
    verificationCode?: string;
    yearsInService?: number;
}
export namespace UserProfile {
    export type RoleEnum = 'CUSTOMER' | 'STORE_ADMIN' | 'STORE' | 'MESSENGER';
    export const RoleEnum = {
        CUSTOMER: 'CUSTOMER' as RoleEnum,
        STOREADMIN: 'STORE_ADMIN' as RoleEnum,
        STORE: 'STORE' as RoleEnum,
        MESSENGER: 'MESSENGER' as RoleEnum
    };
}
